"""Changelog management for BigQuery schema migrations.

Generates and updates CHANGELOG.md with structured entries for each migration,
including Avro compatibility annotations.

Each entry records the migration version, application date, description,
compatibility mode, and migration type so that downstream consumers can
track the schema evolution history in a human-readable format.
"""

import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from .models import Migration, MigrationResult

logger = logging.getLogger(__name__)

_CHANGELOG_HEADER = """\
# Schema CHANGELOG — {dataset}.{table}

This file is auto-generated by `ChangelogManager`. Each entry describes a
versioned schema change applied to the BigQuery table, including its Avro
compatibility classification and migration type.

Compatibility modes follow Apache Avro conventions:
- **BACKWARD**: New readers can read data written by old writers.
- **FORWARD**: Old readers can read data written by new writers.
- **FULL**: Both BACKWARD and FORWARD.

"""


class ChangelogManager:
    """Manages a CHANGELOG.md file that tracks schema migration history.

    The changelog file is written to `changelog_path`. If not provided, it
    defaults to CHANGELOG.md in the current working directory.

    Args:
        changelog_path: Absolute path to the CHANGELOG.md file.
        dataset:        BQ dataset name, used in the file header.
        table:          BQ table name, used in the file header.
    """

    def __init__(
        self,
        changelog_path: Optional[str] = None,
        dataset: str = "my_dataset",
        table: str = "my_table",
    ) -> None:
        self._path = Path(changelog_path or os.path.join(os.getcwd(), "CHANGELOG.md"))
        self._dataset = dataset
        self._table = table

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def add_entry(self, migration: Migration, result: MigrationResult) -> None:
        """Append a new entry to the CHANGELOG.md file.

        If the result was not successful or was already applied, an
        informational note is appended instead of a full entry. If the file
        does not exist it is created with the standard header.

        Args:
            migration: The migration that was applied.
            result:    The MigrationResult from MigrationRunner.apply().
        """
        if result.already_applied:
            logger.debug(
                "Migration %s already applied — not adding duplicate changelog entry.",
                migration.version,
            )
            return

        if not result.success:
            logger.warning(
                "Migration %s failed — not adding changelog entry.",
                migration.version,
            )
            return

        entry = self._format_entry(migration, result)

        if not self._path.exists():
            logger.info("CHANGELOG.md not found — creating with header.")
            self._path.write_text(
                _CHANGELOG_HEADER.format(
                    dataset=self._dataset, table=self._table
                ),
                encoding="utf-8",
            )

        with self._path.open("a", encoding="utf-8") as fh:
            fh.write(entry)

        logger.info(
            "Appended changelog entry for migration %s to %s.",
            migration.version,
            self._path,
        )

    def generate_changelog(self, migrations: List[Migration]) -> str:
        """Generate the full CHANGELOG.md content from a list of migrations.

        Migrations are rendered in reverse order (newest first) so the most
        recent change is at the top of the file after the header. This matches
        the convention used in most CHANGELOG files.

        Args:
            migrations: List of Migration objects (any order; sorted internally
                        by version descending for display).

        Returns:
            Complete CHANGELOG.md file content as a string.
        """
        header = _CHANGELOG_HEADER.format(dataset=self._dataset, table=self._table)

        # Sort newest-first for display; use reverse lexicographic on version.
        sorted_migrations = sorted(
            migrations, key=lambda m: m.version, reverse=True
        )

        sections = [header]
        for migration in sorted_migrations:
            sections.append(self._format_entry(migration, result=None))

        return "".join(sections)

    def write_changelog(self, migrations: List[Migration]) -> None:
        """Write the complete CHANGELOG.md to disk, overwriting any existing file.

        Args:
            migrations: List of Migration objects to include.
        """
        content = self.generate_changelog(migrations)
        self._path.write_text(content, encoding="utf-8")
        logger.info(
            "Wrote CHANGELOG.md with %d migration(s) to %s.",
            len(migrations),
            self._path,
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _format_entry(
        self,
        migration: Migration,
        result: Optional[MigrationResult],
    ) -> str:
        """Format a single changelog entry as a Markdown section.

        Args:
            migration: The migration to document.
            result:    Optional MigrationResult; used to populate applied_at
                       if migration.applied_at is not set.

        Returns:
            Formatted Markdown string for one migration entry.
        """
        applied_date: str
        if migration.applied_at is not None:
            applied_date = migration.applied_at.strftime("%Y-%m-%d")
        else:
            applied_date = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

        column_detail = migration.column_name
        if migration.column_type:
            column_detail = f"{migration.column_name} {migration.column_type}"

        duration_line = ""
        if result is not None and not result.already_applied:
            duration_line = (
                f"**Applied in:** {result.duration_seconds:.3f}s\n\n"
            )

        entry = (
            f"## {migration.version} — {applied_date}\n\n"
            f"**Compatibility:** {migration.compatibility.value}\n\n"
            f"**Migration type:** {migration.migration_type.value}\n\n"
            f"**Column:** {column_detail}\n\n"
            f"**Description:** {migration.description}\n\n"
            f"{duration_line}"
            f"---\n\n"
        )
        return entry
