"""
test_api.py -- FastAPI endpoint tests for the Enterprise Data Quality Framework.

Uses FastAPI TestClient (backed by httpx) to exercise all REST endpoints.
Tests cover both success and error cases (invalid dataset names, etc.).

No external services or database required -- the API loads/generates local CSV data.
"""

import os
import sys

import pytest
from fastapi.testclient import TestClient

# Ensure project root is on sys.path so `from src.xxx` imports work
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from src.api import app

client = TestClient(app)

# The three datasets generated by the framework
VALID_DATASETS = ["customers", "transactions", "products"]
INVALID_DATASET = "nonexistent_dataset_xyz"


# ---------------------------------------------------------------------------
# GET /health
# ---------------------------------------------------------------------------

class TestHealthEndpoint:

    def test_health_returns_200(self):
        resp = client.get("/health")
        assert resp.status_code == 200

    def test_health_status_is_healthy(self):
        resp = client.get("/health")
        body = resp.json()
        assert body["status"] == "healthy"

    def test_health_has_version(self):
        resp = client.get("/health")
        body = resp.json()
        assert "version" in body
        assert body["version"] == "1.0.0"

    def test_health_lists_loaded_datasets(self):
        resp = client.get("/health")
        body = resp.json()
        assert "datasets_loaded" in body
        for ds in VALID_DATASETS:
            assert ds in body["datasets_loaded"]

    def test_health_has_framework_name(self):
        resp = client.get("/health")
        body = resp.json()
        assert "framework" in body


# ---------------------------------------------------------------------------
# GET /datasets
# ---------------------------------------------------------------------------

class TestDatasetsEndpoint:

    def test_datasets_returns_200(self):
        resp = client.get("/datasets")
        assert resp.status_code == 200

    def test_datasets_has_all_three(self):
        resp = client.get("/datasets")
        body = resp.json()
        assert "datasets" in body
        for ds in VALID_DATASETS:
            assert ds in body["datasets"]

    def test_datasets_have_shape_info(self):
        resp = client.get("/datasets")
        body = resp.json()
        for ds in VALID_DATASETS:
            info = body["datasets"][ds]
            assert "rows" in info
            assert "columns" in info
            assert "column_names" in info
            assert info["rows"] > 0
            assert info["columns"] > 0
            assert isinstance(info["column_names"], list)

    def test_datasets_customers_has_expected_columns(self):
        resp = client.get("/datasets")
        body = resp.json()
        cols = body["datasets"]["customers"]["column_names"]
        assert "customer_id" in cols
        assert "email" in cols


# ---------------------------------------------------------------------------
# GET /datasets/{name}/profile
# ---------------------------------------------------------------------------

class TestProfileEndpoint:

    def test_profile_returns_200_for_valid_dataset(self):
        resp = client.get("/datasets/customers/profile")
        assert resp.status_code == 200

    def test_profile_has_expected_keys(self):
        resp = client.get("/datasets/customers/profile")
        body = resp.json()
        for key in ("dataset_name", "row_count", "column_count", "columns",
                     "profiled_at", "duplicate_rows", "duplicate_rate"):
            assert key in body, f"Missing key: {key}"

    def test_profile_dataset_name_matches(self):
        resp = client.get("/datasets/customers/profile")
        body = resp.json()
        assert body["dataset_name"] == "customers"

    def test_profile_columns_have_stats(self):
        resp = client.get("/datasets/customers/profile")
        body = resp.json()
        assert len(body["columns"]) > 0
        col = body["columns"][0]
        for key in ("column", "dtype", "inferred_type", "total_count",
                     "null_count", "null_rate", "distinct_count"):
            assert key in col, f"Missing column profile key: {key}"

    def test_profile_404_for_invalid_dataset(self):
        resp = client.get(f"/datasets/{INVALID_DATASET}/profile")
        assert resp.status_code == 404

    def test_profile_404_body_has_detail(self):
        resp = client.get(f"/datasets/{INVALID_DATASET}/profile")
        body = resp.json()
        assert "detail" in body

    def test_profile_works_for_all_datasets(self):
        for ds in VALID_DATASETS:
            resp = client.get(f"/datasets/{ds}/profile")
            assert resp.status_code == 200
            body = resp.json()
            assert body["dataset_name"] == ds


# ---------------------------------------------------------------------------
# POST /datasets/{name}/validate
# ---------------------------------------------------------------------------

class TestValidateEndpoint:

    def test_validate_returns_200_for_valid_dataset(self):
        resp = client.post("/datasets/customers/validate")
        assert resp.status_code == 200

    def test_validate_report_has_expected_sections(self):
        resp = client.post("/datasets/customers/validate")
        body = resp.json()
        for section in ("metadata", "scorecard", "profile", "validation",
                         "alerts", "recommendations"):
            assert section in body, f"Missing report section: {section}"

    def test_validate_scorecard_has_overall_score(self):
        resp = client.post("/datasets/customers/validate")
        body = resp.json()
        sc = body["scorecard"]
        assert "overall_score" in sc
        assert "overall_grade" in sc
        assert 0 <= sc["overall_score"] <= 100

    def test_validate_validation_section_has_results(self):
        resp = client.post("/datasets/customers/validate")
        body = resp.json()
        v = body["validation"]
        assert "rule_results" in v
        assert "total_rules" in v
        assert "passed_rules" in v
        assert "failed_rules" in v
        assert v["total_rules"] > 0

    def test_validate_404_for_invalid_dataset(self):
        resp = client.post(f"/datasets/{INVALID_DATASET}/validate")
        assert resp.status_code == 404

    def test_validate_works_for_all_datasets(self):
        for ds in VALID_DATASETS:
            resp = client.post(f"/datasets/{ds}/validate")
            assert resp.status_code == 200
            body = resp.json()
            assert body["scorecard"]["dataset_name"] == ds

    def test_validate_metadata_has_framework_info(self):
        resp = client.post("/datasets/customers/validate")
        body = resp.json()
        meta = body["metadata"]
        assert "generated_at" in meta
        assert "framework_version" in meta

    def test_validate_alerts_is_list(self):
        resp = client.post("/datasets/customers/validate")
        body = resp.json()
        assert isinstance(body["alerts"], list)

    def test_validate_recommendations_is_list(self):
        resp = client.post("/datasets/customers/validate")
        body = resp.json()
        assert isinstance(body["recommendations"], list)


# ---------------------------------------------------------------------------
# GET /datasets/{name}/score
# ---------------------------------------------------------------------------

class TestScoreEndpoint:

    def test_score_returns_200_for_valid_dataset(self):
        resp = client.get("/datasets/customers/score")
        assert resp.status_code == 200

    def test_score_has_expected_keys(self):
        resp = client.get("/datasets/customers/score")
        body = resp.json()
        for key in ("dataset_name", "overall_score", "overall_grade",
                     "total_rules", "passed_rules", "failed_rules", "dimensions"):
            assert key in body, f"Missing scorecard key: {key}"

    def test_score_overall_score_in_valid_range(self):
        resp = client.get("/datasets/customers/score")
        body = resp.json()
        assert 0 <= body["overall_score"] <= 100

    def test_score_grade_is_valid_letter(self):
        resp = client.get("/datasets/customers/score")
        body = resp.json()
        assert body["overall_grade"] in ("A", "B", "C", "D", "F")

    def test_score_dimensions_has_all_five(self):
        resp = client.get("/datasets/customers/score")
        body = resp.json()
        for dim in ("completeness", "validity", "uniqueness", "consistency", "freshness"):
            assert dim in body["dimensions"], f"Missing dimension: {dim}"

    def test_score_dimension_has_score_and_grade(self):
        resp = client.get("/datasets/customers/score")
        body = resp.json()
        for dim_name, dim_data in body["dimensions"].items():
            assert "score" in dim_data
            assert "grade" in dim_data

    def test_score_404_for_invalid_dataset(self):
        resp = client.get(f"/datasets/{INVALID_DATASET}/score")
        assert resp.status_code == 404

    def test_score_works_for_all_datasets(self):
        for ds in VALID_DATASETS:
            resp = client.get(f"/datasets/{ds}/score")
            assert resp.status_code == 200
            body = resp.json()
            assert body["dataset_name"] == ds

    def test_score_passed_plus_failed_equals_total(self):
        resp = client.get("/datasets/customers/score")
        body = resp.json()
        assert body["passed_rules"] + body["failed_rules"] == body["total_rules"]


# ---------------------------------------------------------------------------
# GET /datasets/{name}/rules
# ---------------------------------------------------------------------------

class TestRulesEndpoint:

    def test_rules_returns_200_for_valid_dataset(self):
        resp = client.get("/datasets/customers/rules")
        assert resp.status_code == 200

    def test_rules_has_expected_keys(self):
        resp = client.get("/datasets/customers/rules")
        body = resp.json()
        assert "dataset" in body
        assert "rule_count" in body
        assert "rules" in body
        assert body["dataset"] == "customers"

    def test_rules_list_is_nonempty(self):
        resp = client.get("/datasets/customers/rules")
        body = resp.json()
        assert body["rule_count"] > 0
        assert len(body["rules"]) == body["rule_count"]

    def test_rules_have_required_fields(self):
        resp = client.get("/datasets/customers/rules")
        body = resp.json()
        for rule in body["rules"]:
            for key in ("name", "type", "column", "dimension", "severity"):
                assert key in rule, f"Missing rule key: {key}"

    def test_rules_dimensions_are_valid(self):
        resp = client.get("/datasets/customers/rules")
        body = resp.json()
        valid_dims = {"completeness", "validity", "uniqueness", "consistency", "freshness"}
        for rule in body["rules"]:
            assert rule["dimension"] in valid_dims, f"Invalid dimension: {rule['dimension']}"

    def test_rules_severities_are_valid(self):
        resp = client.get("/datasets/customers/rules")
        body = resp.json()
        valid_severities = {"error", "warning", "info"}
        for rule in body["rules"]:
            assert rule["severity"] in valid_severities, f"Invalid severity: {rule['severity']}"

    def test_rules_404_for_invalid_dataset(self):
        resp = client.get(f"/datasets/{INVALID_DATASET}/rules")
        assert resp.status_code == 404

    def test_rules_works_for_all_datasets(self):
        for ds in VALID_DATASETS:
            resp = client.get(f"/datasets/{ds}/rules")
            assert resp.status_code == 200
            body = resp.json()
            assert body["dataset"] == ds
            assert body["rule_count"] > 0


# ---------------------------------------------------------------------------
# GET /summary
# ---------------------------------------------------------------------------

class TestSummaryEndpoint:

    def test_summary_returns_200(self):
        resp = client.get("/summary")
        assert resp.status_code == 200

    def test_summary_has_all_datasets(self):
        resp = client.get("/summary")
        body = resp.json()
        assert "summary" in body
        for ds in VALID_DATASETS:
            assert ds in body["summary"]

    def test_summary_dataset_has_expected_keys(self):
        resp = client.get("/summary")
        body = resp.json()
        for ds in VALID_DATASETS:
            entry = body["summary"][ds]
            # If entry has "error" key, it errored out during scoring — skip
            if "error" in entry:
                continue
            for key in ("overall_score", "overall_grade", "rows",
                        "total_rules", "passed_rules", "failed_rules",
                        "critical_issues", "dimensions"):
                assert key in entry, f"Missing key '{key}' for dataset '{ds}'"

    def test_summary_scores_in_valid_range(self):
        resp = client.get("/summary")
        body = resp.json()
        for ds in VALID_DATASETS:
            entry = body["summary"][ds]
            if "error" in entry:
                continue
            assert 0 <= entry["overall_score"] <= 100

    def test_summary_grades_are_valid(self):
        resp = client.get("/summary")
        body = resp.json()
        for ds in VALID_DATASETS:
            entry = body["summary"][ds]
            if "error" in entry:
                continue
            assert entry["overall_grade"] in ("A", "B", "C", "D", "F")

    def test_summary_dimensions_present(self):
        resp = client.get("/summary")
        body = resp.json()
        for ds in VALID_DATASETS:
            entry = body["summary"][ds]
            if "error" in entry:
                continue
            dims = entry["dimensions"]
            for dim in ("completeness", "validity", "uniqueness", "consistency", "freshness"):
                assert dim in dims


# ---------------------------------------------------------------------------
# GET /concepts
# ---------------------------------------------------------------------------

class TestConceptsEndpoint:

    def test_concepts_returns_200(self):
        resp = client.get("/concepts")
        assert resp.status_code == 200

    def test_concepts_has_title(self):
        resp = client.get("/concepts")
        body = resp.json()
        assert "title" in body

    def test_concepts_has_all_dimensions(self):
        resp = client.get("/concepts")
        body = resp.json()
        assert "dimensions" in body
        for dim in ("completeness", "validity", "uniqueness", "consistency", "freshness"):
            assert dim in body["dimensions"]

    def test_concepts_dimension_has_definition(self):
        resp = client.get("/concepts")
        body = resp.json()
        for dim_name, dim_data in body["dimensions"].items():
            assert "definition" in dim_data
            assert len(dim_data["definition"]) > 0

    def test_concepts_dimension_has_rules_list(self):
        resp = client.get("/concepts")
        body = resp.json()
        for dim_name, dim_data in body["dimensions"].items():
            assert "rules" in dim_data
            assert isinstance(dim_data["rules"], list)
            assert len(dim_data["rules"]) > 0

    def test_concepts_has_scoring_section(self):
        resp = client.get("/concepts")
        body = resp.json()
        assert "scoring" in body
        assert "grades" in body["scoring"]

    def test_concepts_has_architecture_section(self):
        resp = client.get("/concepts")
        body = resp.json()
        assert "architecture" in body
        assert "layers" in body["architecture"]
        assert len(body["architecture"]["layers"]) > 0


# ---------------------------------------------------------------------------
# Error handling — method not allowed, general 404
# ---------------------------------------------------------------------------

class TestErrorHandling:

    def test_get_on_validate_returns_405(self):
        """GET /datasets/{name}/validate should return 405 (POST only)."""
        resp = client.get("/datasets/customers/validate")
        assert resp.status_code == 405

    def test_post_on_health_returns_405(self):
        """POST /health should return 405 (GET only)."""
        resp = client.post("/health")
        assert resp.status_code == 405

    def test_nonexistent_route_returns_404(self):
        """A completely unknown path should return 404."""
        resp = client.get("/this/path/does/not/exist")
        assert resp.status_code == 404

    def test_404_detail_contains_dataset_info(self):
        """Error detail for missing dataset should mention the name."""
        resp = client.get(f"/datasets/{INVALID_DATASET}/profile")
        body = resp.json()
        assert INVALID_DATASET in body["detail"]
