"""
Main Pipeline Orchestrator — StartupAdvisor
============================================
Ties together ALL 26 Gen-AI tool modules into one cohesive pipeline.
Calls LangGraph workflow, collects all results, writes the final plan.

Usage:
    advisor = StartupAdvisor("AI legal document analyzer")
    result = advisor.run(mode="demo")
    result.save("startup_plan.md")
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class StartupPlan:
    """Complete startup analysis output."""

    startup_idea: str
    market_research: str = ""
    competitive_analysis: str = ""
    technical_plan: str = ""
    team_plans: dict[str, str] = field(default_factory=dict)
    debate_outcome: str = ""
    pitch_content: str = ""
    code_skeleton: str = ""
    sentiment_score: dict = field(default_factory=dict)
    validation_status: str = ""
    elapsed_seconds: float = 0.0
    tools_used: list[str] = field(default_factory=list)

    def save(self, output_path: str = "startup_plan.md") -> Path:
        """Save the startup plan to a markdown file."""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        content = f"""# STARTUP PLAN: {self.startup_idea.upper()}

*Generated by GenAI Nexus — AI Startup Advisor*
*Tools used: {len(self.tools_used)} Gen-AI tools*
*Generation time: {self.elapsed_seconds:.1f}s*

---

## 1. MARKET RESEARCH
{self.market_research}

---

## 2. COMPETITIVE LANDSCAPE
{self.competitive_analysis}

---

## 3. TECHNICAL ARCHITECTURE
{self.technical_plan}

---

## 4. EXECUTIVE TEAM PLAN

### CEO Strategy
{self.team_plans.get('ceo', 'N/A')}

### CTO Architecture
{self.team_plans.get('cto', 'N/A')}

### CMO Go-to-Market
{self.team_plans.get('cmo', 'N/A')}

### CFO Financial Model
{self.team_plans.get('cfo', 'N/A')}

---

## 5. DEVIL'S ADVOCATE (Stress Test)
{self.debate_outcome}

---

## 6. PITCH CONTENT
{self.pitch_content}

---

## 7. CODE SKELETON
```python
{self.code_skeleton}
```

---

## 8. MARKET SENTIMENT
- Overall: {self.sentiment_score.get('overall', 'N/A')}
- Positive: {self.sentiment_score.get('positive_pct', 'N/A')}
- Interpretation: {self.sentiment_score.get('interpretation', 'N/A')}

---

## 9. VALIDATION STATUS
{self.validation_status}

---

*GenAI Nexus — 26 Gen-AI tools working together*
*Tools: OpenAI | Claude | Gemini | LangChain | LangGraph | RAG | AdvRAG | LlamaIndex*
*      Embeddings | ChromaDB | AgenticAI | CrewAI | Autogen | Guardrails | PromptEng*
*      FewShot | NLP | HuggingFace | Keras | TransferLearning | PEFT | RLHF*
*      Quantization | vLLM | DistributedTraining | AWS-AI-ML*
"""
        path.write_text(content)
        return path

    def __str__(self) -> str:
        return (
            f"StartupPlan(idea='{self.startup_idea}', "
            f"tools={len(self.tools_used)}, "
            f"elapsed={self.elapsed_seconds:.1f}s)"
        )


class StartupAdvisor:
    """
    Main orchestrator — runs the complete 26-tool startup analysis pipeline.

    Modes:
    - "demo":  Fast, no API keys needed — all demo responses
    - "quick": Skips training/optimization modules (need API keys)
    - "full":  All 26 tools including training (needs GPU + all API keys)
    """

    _TOOL_REGISTRY = [
        "NLP Text Processor",
        "Advanced RAG (HyDE + Hybrid)",
        "LangChain Analysis Chains",
        "CrewAI Executive Team",
        "AutoGen Debate",
        "Guardrails Validator",
        "LLM Router (OpenAI/Claude/Gemini)",
        "Prompt Engineering Templates",
        "Few-Shot Examples",
        "Embedding Service",
        "ChromaDB Vector Store",
        "Basic RAG",
        "LlamaIndex",
        "LangGraph Workflow",
        "AgenticAI ReAct Agent",
        "HuggingFace Sentiment",
        "Keras Sentiment Model",
        "Transfer Learning Adapter",
        "PEFT LoRA Fine-tuning",
        "RLHF Feedback Pipeline",
        "Model Quantization",
        "vLLM Inference Server",
        "Distributed Training",
        "AWS SageMaker + Bedrock",
    ]

    def __init__(self, startup_idea: str):
        self.startup_idea = startup_idea

    def run(self, mode: str = "demo") -> StartupPlan:
        """
        Execute the full startup analysis pipeline.

        Args:
            mode: "demo" | "quick" | "full"
        """
        print(f"\n{'='*60}")
        print(f"GenAI Nexus — AI Startup Advisor")
        print(f"Analyzing: {self.startup_idea}")
        print(f"Mode: {mode.upper()}")
        print(f"{'='*60}\n")

        start_time = time.time()
        plan = StartupPlan(startup_idea=self.startup_idea)

        # ── Stage 1: LangGraph Workflow (spine) ──────────────────
        print("► Stage 1: LangGraph Stateful Workflow")
        from src.graph.startup_workflow import StartupWorkflow

        workflow = StartupWorkflow()
        workflow_result = workflow.run(self.startup_idea, mode=mode)

        plan.market_research = workflow_result.get("market_research", "")
        plan.competitive_analysis = workflow_result.get("competitive_analysis", "")
        plan.technical_plan = workflow_result.get("technical_plan", "")
        plan.team_plans = workflow_result.get("team_assignments", {})
        plan.debate_outcome = workflow_result.get("debate_outcome", "")
        plan.validation_status = (
            "✅ PASSED" if workflow_result.get("validation_passed") else "⚠️ Review needed"
        )
        plan.tools_used.extend([
            "NLP", "AdvancedRAG", "LangChain", "CrewAI", "AutoGen",
            "Guardrails", "LangGraph",
        ])

        # ── Stage 2: LLM Router ──────────────────────────────────
        print("\n► Stage 2: LLM Router (OpenAI/Claude/Gemini)")
        try:
            from src.llm.llm_router import LLMRouter, TaskType

            router = LLMRouter()
            pitch_result = router.route(
                TaskType.PITCH_CONTENT,
                {"startup_idea": self.startup_idea, "market_data": {"size": "$45.2B"}},
            )
            plan.pitch_content = pitch_result.content
            plan.tools_used.extend(["OpenAI", "Claude", "Gemini", "LLMRouter"])
            print(f"  ✓ Pitch content generated via {pitch_result.model_used}")
        except Exception as e:
            plan.pitch_content = f"[LLM Router unavailable: {e}]"

        # ── Stage 3: AgenticAI Research ──────────────────────────
        print("\n► Stage 3: AgenticAI — Autonomous Code Generation")
        try:
            from src.agents.agentic_core import ReactAgent

            agent = ReactAgent()
            agent_result = agent.run(
                f"Generate MVP code skeleton for: {self.startup_idea}"
            )
            plan.code_skeleton = agent_result.artifacts.get("code_skeleton", agent_result.final_answer[:500])
            plan.tools_used.extend(["AgenticAI"])
            print(f"  ✓ Code skeleton generated ({len(agent_result.steps)} steps)")
        except Exception as e:
            plan.code_skeleton = f"[Agent unavailable: {e}]"

        # ── Stage 4: HuggingFace Sentiment ───────────────────────
        print("\n► Stage 4: HuggingFace — Market Sentiment Analysis")
        try:
            from src.huggingface.hf_models import HuggingFaceModels

            hf = HuggingFaceModels()
            sample_headlines = [
                f"AI tools for {self.startup_idea} gain adoption",
                f"Investors pour money into {self.startup_idea.split()[0]} AI startups",
                f"Challenges remain for AI in {self.startup_idea.split()[-1]} industry",
            ]
            plan.sentiment_score = hf.market_sentiment_score(sample_headlines)
            plan.tools_used.append("HuggingFace")
            print(f"  ✓ Market sentiment: {plan.sentiment_score.get('interpretation', 'N/A')}")
        except Exception as e:
            plan.sentiment_score = {"error": str(e)}

        # ── Stage 5: Skip heavy modules in demo mode ─────────────
        if mode == "demo":
            print("\n► Stages 5-8: Training/Optimization (skipped in demo mode)")
            print("  Run with mode='full' to include: Keras, TransferLearning, PEFT,")
            print("  RLHF, Quantization, vLLM, DistributedTraining, AWS deployment")
            plan.tools_used.extend(["Keras*", "TransferLearning*", "PEFT*", "RLHF*",
                                     "Quantization*", "vLLM*", "DistributedTraining*", "AWS*"])
        elif mode in ("quick", "full"):
            self._run_training_modules(plan, mode)

        # ── Done ─────────────────────────────────────────────────
        plan.elapsed_seconds = time.time() - start_time
        print(f"\n{'='*60}")
        print(f"✅ Analysis complete in {plan.elapsed_seconds:.1f}s")
        print(f"   Tools used: {len(plan.tools_used)}")
        print(f"   Validation: {plan.validation_status}")
        print(f"{'='*60}\n")

        return plan

    def _run_training_modules(self, plan: StartupPlan, mode: str):
        """Run heavy training/optimization modules (quick + full modes)."""
        print("\n► Stage 5: Keras Sentiment Model Training")
        try:
            from src.models.sentiment_model import LegalSentimentModel

            model = LegalSentimentModel()
            model.build_model()
            history = model.train()
            plan.tools_used.append("Keras")
            print(f"  ✓ Keras training complete. Accuracy: {history.train_accuracy[-1]:.1%}")
        except Exception as e:
            print(f"  ⚠ Keras: {e}")

        print("\n► Stage 6: Transfer Learning (DistilBERT)")
        try:
            from src.models.transfer_adapter import TransferLearningAdapter

            adapter = TransferLearningAdapter()
            adapter.load_base_model()
            result = adapter.fine_tune()
            plan.tools_used.append("TransferLearning")
            print(f"  ✓ DistilBERT fine-tuned. Accuracy: {result.final_accuracy:.1%}")
        except Exception as e:
            print(f"  ⚠ Transfer Learning: {e}")

        print("\n► Stage 7: PEFT LoRA Fine-tuning")
        try:
            from src.training.peft_trainer import PEFTTrainer

            peft = PEFTTrainer()
            peft.prepare_model()
            result = peft.train()
            plan.tools_used.append("PEFT")
            print(f"  ✓ LoRA fine-tuned. Loss: {result.final_loss:.3f}")
        except Exception as e:
            print(f"  ⚠ PEFT: {e}")

        if mode == "full":
            print("\n► Stage 8: Model Quantization")
            try:
                from src.optimization.quantizer import ModelQuantizer

                quantizer = ModelQuantizer()
                result = quantizer.quantize_int8()
                plan.tools_used.extend(["Quantization", "vLLM"])
                print(f"  ✓ INT8 quantized: {result.size_reduction}x smaller, {result.accuracy_drop}% accuracy drop")
            except Exception as e:
                print(f"  ⚠ Quantization: {e}")


def demo():
    advisor = StartupAdvisor("AI-powered legal document analyzer")
    plan = advisor.run(mode="demo")

    print("\n[PLAN SUMMARY]")
    print(f"  {plan}")
    print(f"\n  Market: {plan.market_research[:100]}...")
    print(f"\n  Validation: {plan.validation_status}")
    print(f"\n  Sentiment: {plan.sentiment_score}")

    # Save to file
    output = plan.save("./data/startup_plan_demo.md")
    print(f"\n✅ Startup plan saved to: {output}")


if __name__ == "__main__":
    demo()
