"""
Gen-AI Tool: Local LLM (Ollama)
=================================
Demonstrates: Local LLM inference via Ollama, OpenAI-compatible API,
model selection per task, streaming, and function calling with LLaMA.

Role in GenAI Nexus: Run the ENTIRE pipeline locally — zero cloud API
calls, zero API keys, zero cost. Uses LLaMA 3 models via Ollama.

Prerequisites:
    brew install ollama && ollama serve
    ollama pull llama3.1:8b
    ollama pull codellama:7b
    ollama pull llama3.2:3b
    ollama pull nomic-embed-text
"""

from __future__ import annotations

import hashlib
import math
import random
from dataclasses import dataclass, field
from typing import Generator

# Demo responses for each task (mirrors OpenAI client pattern)
DEMO_MARKET = """
MARKET ANALYSIS (Local LLaMA — Demo Mode)
==========================================
Total Addressable Market (TAM): $45.2B — Global legal tech market
Serviceable Addressable Market (SAM): $8.1B — AI-powered legal tools
Serviceable Obtainable Market (SOM): $810M — Mid-market AI doc analysis

Growth Rate: 18.9% CAGR through 2030
Key Drivers: AI adoption acceleration, remote work, regulatory complexity
Risk Factors: Attorney-client privilege, state bar regulations, data security

Market Segments:
1. Contract Management: 28% ($12.7B) — Fastest growing
2. eDiscovery: 22% ($9.9B) — Established, competitive
3. Legal Research: 18% ($8.1B) — Disrupted by AI rapidly
4. Document Review: 15% ($6.8B) — Our primary target

Investment: $2.1B VC invested in legal tech in 2023
Adoption: 73% of law firms plan AI by 2025 (Thomson Reuters survey)
"""

DEMO_COMPETITOR = """
COMPETITIVE ANALYSIS (Local LLaMA — Demo Mode)
===============================================
1. Harvey AI — BigLaw focus, $100M Series B, GPT-4 powered
   - Weakness: $5K+/month, only serves Am Law 200
2. Ironclad — Enterprise CLM, $333M total, not AI-first
   - Weakness: Contract lifecycle, not analysis
3. Kira Systems — Acquired by Litera, due diligence focus
   - Weakness: M&A-only, outdated tech stack

GAP IDENTIFIED: Mid-market firms (1-50 attorneys) — $299-$999/month
No AI-native solution exists at this price point.
"""

DEMO_CODE = '''
# MVP Code Skeleton — AI Legal Document Analyzer
# Generated by Local LLaMA (CodeLlama)

from dataclasses import dataclass
from fastapi import FastAPI, UploadFile

@dataclass
class ContractRisk:
    score: float  # 0.0 to 1.0
    clauses: list[str]
    red_flags: list[str]

class LegalDocumentProcessor:
    """Core document analysis engine."""

    def __init__(self, model_endpoint: str = "http://localhost:11434"):
        self.endpoint = model_endpoint

    def analyze(self, document: str) -> ContractRisk:
        # 1. Extract clauses using NER
        # 2. Score risk per clause using LLM
        # 3. Aggregate into overall risk score
        return ContractRisk(
            score=0.35,
            clauses=["§3.2 Limitation of Liability", "§7 Indemnification"],
            red_flags=["Unlimited indemnification clause detected"],
        )

app = FastAPI(title="LegalAI — Document Analyzer")

@app.post("/analyze")
async def analyze_document(file: UploadFile):
    text = (await file.read()).decode()
    processor = LegalDocumentProcessor()
    result = processor.analyze(text)
    return {"risk_score": result.score, "red_flags": result.red_flags}
'''

DEMO_PITCH = """
ELEVATOR PITCH (Local LLaMA — Demo Mode)
==========================================
"Legal review costs US law firms $180B per year. 40% is pure waste.

LegalAI analyzes contracts in 90 seconds — what takes a junior associate
4 hours. We serve mid-market firms at $299/month, a segment that Harvey AI
and Ironclad completely ignore.

50 beta users. NPS of 72. 85% week-over-week retention.

We're raising $1.5M to reach 500 customers in 18 months."

SLIDE DECK:
1. Hook: "$180B wasted on manual legal review"
2. Problem: 40% of attorney time on document review
3. Solution: 90-second AI analysis, risk scoring, clause suggestions
4. Market: $45.2B TAM, 18.9% CAGR, 73% firms adopting AI
5. Traction: 50 beta, NPS 72, 3 paid pilots
6. Business Model: $299/$999/Enterprise per month
7. Competition: Harvey (BigLaw) + Ironclad (Enterprise) = mid-market gap
8. Team: Ex-BigLaw CEO, Ex-Google CTO, Ex-Clio CMO
9. Financials: $150K ARR M12, $2M ARR M24, profitable M36
10. Ask: $1.5M seed, 18mo runway, 500 customers
"""


@dataclass
class OllamaConfig:
    """Configuration for Ollama local LLM."""

    base_url: str = "http://localhost:11434"
    default_model: str = "llama3.1:8b"
    code_model: str = "codellama:7b"
    fast_model: str = "llama3.2:3b"
    embedding_model: str = "nomic-embed-text"
    temperature: float = 0.3
    max_tokens: int = 2048
    timeout: int = 120


@dataclass
class OllamaResponse:
    """Response from Ollama LLM call."""

    content: str
    model: str
    tokens_used: int = 0
    metadata: dict = field(default_factory=dict)


class OllamaClient:
    """
    Local LLM client via Ollama.

    Uses Ollama's OpenAI-compatible API at localhost:11434/v1.
    Mirrors the interface of OpenAIClient for seamless Router integration.

    Features:
    - Multiple model selection per task (general, code, fast)
    - Streaming support
    - Local embeddings via nomic-embed-text
    - Auto-detection of Ollama availability
    - Graceful demo fallback when Ollama is not running
    """

    def __init__(self, config: OllamaConfig | None = None):
        self.config = config or OllamaConfig()
        self._available = False
        self._client = None
        self._demo = True
        self._model_names: list[str] = []

        try:
            from openai import OpenAI

            # Short-timeout client just for the init health check (3s)
            probe = OpenAI(
                base_url=f"{self.config.base_url}/v1",
                api_key="ollama",
                timeout=3.0,
            )
            models = probe.models.list()
            self._model_names = [m.id for m in models.data] if models.data else []

            # Health check passed — create the real client with configured timeout
            self._client = OpenAI(
                base_url=f"{self.config.base_url}/v1",
                api_key="ollama",
                timeout=self.config.timeout,
            )
            self._available = True
            self._demo = False
        except Exception:
            self._available = False
            self._demo = True
            self._model_names = []

    @property
    def is_available(self) -> bool:
        """Check if Ollama server is reachable and responding."""
        return self._available

    @property
    def available_models(self) -> list[str]:
        """List models currently loaded in Ollama."""
        return self._model_names

    def analyze_market(self, startup_idea: str) -> OllamaResponse:
        """Market research using local LLaMA."""
        return self._chat(
            model=self.config.default_model,
            system=(
                "You are an expert market analyst specializing in startups and venture capital. "
                "Provide TAM/SAM/SOM analysis with specific numbers. Be data-driven and concise."
            ),
            user=f"Analyze the market opportunity for this startup idea: {startup_idea}",
        )

    def analyze_competitors(self, startup_idea: str) -> OllamaResponse:
        """Competitive intelligence using local LLaMA."""
        return self._chat(
            model=self.config.default_model,
            system=(
                "You are a competitive intelligence analyst. Identify key competitors, "
                "their funding, positioning, strengths, weaknesses, and market gaps."
            ),
            user=f"Map the competitive landscape for: {startup_idea}",
        )

    def generate_code(
        self, startup_idea: str, tech_stack: list[str] | None = None
    ) -> OllamaResponse:
        """MVP code skeleton using CodeLlama."""
        stack = ", ".join(tech_stack or ["Python", "FastAPI"])
        return self._chat(
            model=self.config.code_model,
            system=(
                "You are an expert software architect. Generate a production-ready "
                "MVP code skeleton with proper structure, error handling, and type hints."
            ),
            user=f"Generate a code skeleton for: {startup_idea}\nTech stack: {stack}",
        )

    def generate_pitch(
        self, startup_idea: str, market_data: dict | None = None
    ) -> OllamaResponse:
        """Pitch content using fast model for quick generation."""
        market_context = ""
        if market_data:
            market_context = f"\nMarket data: {market_data}"
        return self._chat(
            model=self.config.fast_model,
            system=(
                "You are an expert startup pitch advisor. Create compelling, "
                "data-driven pitch content. Be specific with numbers."
            ),
            user=f"Create a 30-second elevator pitch and 10-slide deck outline for: {startup_idea}{market_context}",
        )

    def fast_summary(self, text: str) -> OllamaResponse:
        """Quick summary using the smallest/fastest model."""
        return self._chat(
            model=self.config.fast_model,
            system="Summarize concisely. Be direct and specific.",
            user=f"Summarize: {text}",
        )

    def stream(
        self, prompt: str, model: str | None = None
    ) -> Generator[str, None, None]:
        """Streaming generation — yields tokens as they arrive."""
        if self._demo:
            for word in f"[Demo local] Response for: {prompt[:80]}".split():
                yield word + " "
            return

        response = self._client.chat.completions.create(
            model=model or self.config.default_model,
            messages=[{"role": "user", "content": prompt}],
            temperature=self.config.temperature,
            stream=True,
        )
        for chunk in response:
            delta = chunk.choices[0].delta
            if delta and delta.content:
                yield delta.content

    def _chat(self, model: str, system: str, user: str) -> OllamaResponse:
        """Core chat completion call to Ollama."""
        if self._demo:
            # Return appropriate demo content based on prompt keywords
            return self._demo_response(model, user)

        response = self._client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            temperature=self.config.temperature,
            max_tokens=self.config.max_tokens,
        )
        return OllamaResponse(
            content=response.choices[0].message.content or "",
            model=model,
            tokens_used=response.usage.total_tokens if response.usage else 0,
        )

    def _demo_response(self, model: str, user_prompt: str) -> OllamaResponse:
        """Generate appropriate demo response based on prompt content."""
        prompt_lower = user_prompt.lower()
        if "competitor" in prompt_lower or "competitive" in prompt_lower:
            content = DEMO_COMPETITOR
        elif "code" in prompt_lower or "skeleton" in prompt_lower or "generate" in prompt_lower:
            content = DEMO_CODE
        elif "pitch" in prompt_lower or "elevator" in prompt_lower:
            content = DEMO_PITCH
        elif "summar" in prompt_lower:
            content = f"[Demo local — {model}] Summary: {user_prompt[:100]}..."
        else:
            content = DEMO_MARKET

        return OllamaResponse(
            content=content,
            model="demo-local",
            tokens_used=0,
        )

    def embed(self, texts: list[str]) -> list[list[float]]:
        """
        Local embeddings via Ollama's nomic-embed-text model.
        Returns 768-dimensional vectors.
        """
        if self._demo:
            # Deterministic fake embeddings (same text → same vector)
            results = []
            for text in texts:
                seed = int(hashlib.md5(text.encode()).hexdigest(), 16) % (2**32)
                rng = random.Random(seed)
                raw = [rng.gauss(0, 1) for _ in range(768)]
                mag = math.sqrt(sum(x * x for x in raw))
                results.append([x / mag for x in raw])
            return results

        import requests

        results = []
        for text in texts:
            resp = requests.post(
                f"{self.config.base_url}/api/embeddings",
                json={"model": self.config.embedding_model, "prompt": text},
                timeout=self.config.timeout,
            )
            resp.raise_for_status()
            results.append(resp.json()["embedding"])
        return results

    def health_check(self) -> dict:
        """Check Ollama server status and available models."""
        return {
            "available": self._available,
            "base_url": self.config.base_url,
            "models": self._model_names,
            "default_model": self.config.default_model,
            "code_model": self.config.code_model,
            "fast_model": self.config.fast_model,
        }


def demo():
    """Demo the Ollama local LLM client."""
    print("=" * 60)
    print("DEMO: Local LLM via Ollama")
    print("=" * 60)

    client = OllamaClient()
    health = client.health_check()

    if client.is_available:
        print(f"✅ Ollama is running at {client.config.base_url}")
        print(f"   Models: {', '.join(client.available_models)}")
    else:
        print("⚠️  Ollama not running — using demo mode")
        print("   Install: brew install ollama && ollama serve")
        print("   Models:  ollama pull llama3.1:8b")

    print(f"\n[1] Market Analysis (model: {client.config.default_model})")
    result = client.analyze_market("AI-powered legal document analyzer")
    print(f"  Model: {result.model}")
    print(f"  Response: {result.content[:300]}...")

    print(f"\n[2] Competitor Analysis (model: {client.config.default_model})")
    result = client.analyze_competitors("AI legal document analyzer")
    print(f"  Model: {result.model}")
    print(f"  Response: {result.content[:300]}...")

    print(f"\n[3] Code Generation (model: {client.config.code_model})")
    code = client.generate_code("AI legal analyzer", ["Python", "FastAPI"])
    print(f"  Model: {code.model}")
    print(f"  Response: {code.content[:300]}...")

    print(f"\n[4] Pitch Content (model: {client.config.fast_model})")
    pitch = client.generate_pitch("AI legal analyzer", {"tam": "$45.2B"})
    print(f"  Model: {pitch.model}")
    print(f"  Response: {pitch.content[:300]}...")

    print(f"\n[5] Streaming Example")
    print("  ", end="")
    for token in client.stream("Explain RAG in one sentence"):
        print(token, end="", flush=True)
    print()

    print(f"\n[6] Local Embeddings")
    embeddings = client.embed(["AI legal tools", "contract analysis"])
    for i, emb in enumerate(embeddings):
        print(f"  Text {i+1}: {len(emb)} dimensions, norm={sum(x*x for x in emb):.2f}")

    print(f"\n[7] Health Check")
    for k, v in health.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    demo()
